title = "ai-kit gitleaks config"

[allowlist]
description = "Allowlist for notebook metadata and false positives"

# Ignore hex strings in notebook metadata (not actual secrets)
# These are hashed_secret values from the old detect-secrets baseline
regexes = [
  '''\"hashed_secret\": \"[a-f0-9]{40}\"''',
  '''\"id\": \"[a-f0-9-]{36}\"'''
]

# Use default Gitleaks rules for all other patterns
# Gitleaks will detect AWS keys, GitHub tokens, private keys, etc.
