fail_fast: true
default_stages: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Run the linter (with automatic fixes)
      - id: ruff-check
        args: [--fix]
      # Run the formatter (automatically formats)
      - id: ruff-format

  # Notebook linting with nbqa (optional, non-blocking)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-ruff
        args: [--fix]
        files: ^notebooks/.*\.ipynb$
        # Non-blocking: don't fail on linting errors in notebooks
        verbose: true
        # Only warn, don't block commits
        stages: [manual]

  # Notebook output stripping
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: ^notebooks/.*\.ipynb$

  # Secret scanning (TruffleHog - pre-commit blocking)
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --fail'
        language: system
        stages: ["pre-commit", "pre-push"]

  # Custom notebook validation hooks
  - repo: local
    hooks:
      - id: notebook-metadata-validation
        name: Validate notebook metadata
        entry: uv run --directory apps/cli python -m ai_kit.cli.core.validators --check-metadata
        language: system
        files: ^notebooks/.*\.ipynb$
        pass_filenames: true

      - id: notebook-size-check
        name: Check notebook file size
        entry: uv run --directory apps/cli python -m ai_kit.cli.core.validators --check-size
        language: system
        files: ^notebooks/.*\.ipynb$
        pass_filenames: true
