[project]
name = "ai-kit-core"
version = "0.1.0"
description = "Core library for ai-kit"
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
