name: Pre-commit

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Run pre-commit on all files
        run: uv run pre-commit run --all-files
